//
//  SKStyles.m
//  SensingKit-iOS
//
//  Created by Kleomenis Katevas on 23/11/2015.
//  Copyright (c) 2015 Queen Mary University of London. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "SKStyles.h"

// MARK: - Safe dynamic color helpers for pre–iOS 13 fallback
static inline UIColor *SKSystemBackgroundColor(void) {
    if (@available(iOS 13.0, *)) {
        return UIColor.systemBackgroundColor;
    } else {
        return [UIColor whiteColor];
    }
}

static inline UIColor *SKLabelColor(void) {
    if (@available(iOS 13.0, *)) {
        return UIColor.labelColor;
    } else {
        return [UIColor blackColor];
    }
}

static inline UIColor *SKSystemBlueTint(void) {
    if (@available(iOS 13.0, *)) {
        return UIColor.systemBlueColor;
    } else {
        return [UIColor colorWithRed:0.0 green:122.0/255.0 blue:1.0 alpha:1.0];
    }
}

static inline UIColor *SKDynamicColor(UIColor *lightColor, UIColor *darkColor) {
    if (@available(iOS 13.0, *)) {
        return [UIColor colorWithDynamicProvider:^UIColor * _Nonnull(UITraitCollection * _Nonnull traitCollection) {
            return (traitCollection.userInterfaceStyle == UIUserInterfaceStyleDark) ? darkColor : lightColor;
        }];
    } else {
        return lightColor;
    }
}

@implementation SKStyles

#pragma mark Cache

static UIColor* _backgroundColor = nil;

#pragma mark Initialization

+ (void)initialize
{
    UIColor *tint = [UIColor colorNamed:@"SKStyleTint"];
    if (tint == nil) {
        // Fallback to system tint that adapts to light/dark
        tint = SKSystemBlueTint();
    }
    _backgroundColor = tint;
}

#pragma mark Colors

+ (UIColor*)backgroundColor { return _backgroundColor; }

#pragma mark Drawing Methods

+ (void)drawRoundButtonFilledWithTitle: (NSString*)title
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor *titleColor = SKSystemBackgroundColor();

    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(3.5, 3.5, 65, 65)];
    [[SKStyles backgroundColor] setFill];
    [ovalPath fill];


    //// Text Drawing
    CGRect textRect = CGRectMake(0, 25, 72, 21);
    NSMutableParagraphStyle* textStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    textStyle.alignment = NSTextAlignmentCenter;

    NSDictionary* textFontAttributes = @{NSFontAttributeName: [UIFont preferredFontForTextStyle:UIFontTextStyleBody], NSForegroundColorAttributeName: titleColor, NSParagraphStyleAttributeName: textStyle};

    CGFloat textTextHeight = [title boundingRectWithSize: CGSizeMake(textRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: textFontAttributes context: nil].size.height;
    CGContextSaveGState(context);
    CGContextClipToRect(context, textRect);
    [title drawInRect: CGRectMake(CGRectGetMinX(textRect), CGRectGetMinY(textRect) + (CGRectGetHeight(textRect) - textTextHeight) / 2, CGRectGetWidth(textRect), textTextHeight) withAttributes: textFontAttributes];
    CGContextRestoreGState(context);
}

+ (void)drawRoundButtonFilledDeactivatedWithTitle: (NSString*)title
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor *titleColor = SKLabelColor();
    UIColor *deactivatedColor = SKDynamicColor([UIColor colorWithWhite:0.0 alpha:0.2], [UIColor colorWithWhite:1.0 alpha:0.28]);

    //// Oval Drawing
    [deactivatedColor setFill];
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(3.5, 3.5, 65, 65)];
    [ovalPath fill];


    //// Text Drawing
    CGRect textRect = CGRectMake(0, 25, 72, 21);
    NSMutableParagraphStyle* textStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    textStyle.alignment = NSTextAlignmentCenter;

    NSDictionary* textFontAttributes = @{NSFontAttributeName: [UIFont preferredFontForTextStyle:UIFontTextStyleBody], NSForegroundColorAttributeName: titleColor, NSParagraphStyleAttributeName: textStyle};

    CGFloat textTextHeight = [title boundingRectWithSize: CGSizeMake(textRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: textFontAttributes context: nil].size.height;
    CGContextSaveGState(context);
    CGContextClipToRect(context, textRect);
    [title drawInRect: CGRectMake(CGRectGetMinX(textRect), CGRectGetMinY(textRect) + (CGRectGetHeight(textRect) - textTextHeight) / 2, CGRectGetWidth(textRect), textTextHeight) withAttributes: textFontAttributes];
    CGContextRestoreGState(context);
}

+ (void)drawRoundButtonStrokedWithTitle: (NSString*)title
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(3.5, 3.5, 65, 65)];
    [SKSystemBackgroundColor() setFill];
    [ovalPath fill];
    [[SKStyles backgroundColor] setStroke];
    ovalPath.lineWidth = 1.0;
    [ovalPath stroke];


    //// Text Drawing
    CGRect textRect = CGRectMake(0, 25, 72, 21);
    NSMutableParagraphStyle* textStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    textStyle.alignment = NSTextAlignmentCenter;

    NSDictionary* textFontAttributes = @{NSFontAttributeName: [UIFont preferredFontForTextStyle:UIFontTextStyleBody], NSForegroundColorAttributeName: [SKStyles backgroundColor], NSParagraphStyleAttributeName: textStyle};

    CGFloat textTextHeight = [title boundingRectWithSize: CGSizeMake(textRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: textFontAttributes context: nil].size.height;
    CGContextSaveGState(context);
    CGContextClipToRect(context, textRect);
    [title drawInRect: CGRectMake(CGRectGetMinX(textRect), CGRectGetMinY(textRect) + (CGRectGetHeight(textRect) - textTextHeight) / 2, CGRectGetWidth(textRect), textTextHeight) withAttributes: textFontAttributes];
    CGContextRestoreGState(context);
}

+ (void)drawRoundButtonStrokedDeactivatedWithTitle: (NSString*)title
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor *deactivatedColor = SKDynamicColor([UIColor colorWithWhite:0.0 alpha:0.2], [UIColor colorWithWhite:1.0 alpha:0.28]);

    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(3.5, 3.5, 65, 65)];
    [SKSystemBackgroundColor() setFill];
    [ovalPath fill];
    [deactivatedColor setStroke];
    ovalPath.lineWidth = 1;
    [ovalPath stroke];


    //// Text Drawing
    CGRect textRect = CGRectMake(0, 25, 72, 21);
    NSMutableParagraphStyle* textStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    textStyle.alignment = NSTextAlignmentCenter;

    NSDictionary* textFontAttributes = @{NSFontAttributeName: [UIFont preferredFontForTextStyle:UIFontTextStyleBody], NSForegroundColorAttributeName: deactivatedColor, NSParagraphStyleAttributeName: textStyle};

    CGFloat textTextHeight = [title boundingRectWithSize: CGSizeMake(textRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: textFontAttributes context: nil].size.height;
    CGContextSaveGState(context);
    CGContextClipToRect(context, textRect);
    [title drawInRect: CGRectMake(CGRectGetMinX(textRect), CGRectGetMinY(textRect) + (CGRectGetHeight(textRect) - textTextHeight) / 2, CGRectGetWidth(textRect), textTextHeight) withAttributes: textFontAttributes];
    CGContextRestoreGState(context);
}

@end

