//
//  SKStyles.h
//  SensingKit-iOS
//
//  Created by Kleomenis Katevas on 07/11/2014.
//  Copyright (c) 2014 Queen Mary University of London. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface SKStyles : NSObject

// Colors
+ (UIColor*)backgroundColor;

// Drawing Methods
+ (void)drawRoundButtonFilledWithTitle: (NSString*)title;
+ (void)drawRoundButtonStrokedWithTitle: (NSString*)title;

@end
